### ISSUE TITLE
Registration Julio

### ISSUE THREAD

**Issue by matthiasjost** [WeAreDotnet/dotnet-creator-cards#100]
@julioct Hey Julio, could you register as a Member? I cannot verify you as a creator without signing up as a member (I accepted the PR already: https://github.com/WeAreDotnet/dotnet-creator-cards/pull/99)
Greetings Matthias

**Comment by matthiasjost** [comment]
I found you. Something else is wrong here. Let me check...

**Comment by matthiasjost** [comment]
Now I can see your card: https://www.wearedotnet.io/julioct, not sure what was wrong before but you are verified as a creator now.

**Comment by julioct** [comment]
Great, thank you!
