### ISSUE TITLE
Exclude RSS feed from creator on landing and content page

### ISSUE THREAD

**Issue by matthiasjost** [WeAreDotnet/dotnet-creator-cards#104]
- We should exclude feeds with RSS trial app-ended messages.

- An API option to temporarily exclude a creator's content would be helpful (landing and content page)

**Comment by matthiasjost** [comment]
@DeeJayTC Isn't this already solved? Do we already have an API endpoint for disabling a creator's content aggregation?

**Comment by DeeJayTC** [comment]
Only to completely disable one including profile, and not deployed yet
