### ISSUE TITLE
"x hours ago" is wrong

### ISSUE THREAD

**Issue by ursenzler** [WeAreDotnet/dotnet-creator-cards#110]
**Not important**, but I just stumbled over it. After writing a new blog post, it is shown in my feed (crazy fast btw!), but it is shown as "2 hours ago".
I guess a problem with local time vs UTC (I'm on 2 hours offset).

**Comment by DeeJayTC** [comment]
Yea we store UTC dates and apparently the library used to format the time isn't timezone aware....gotta fix that!

**Comment by DeeJayTC** [comment]
Fixed in next deployment
