### ISSUE TITLE
[Bug] feed not processed

### ISSUE THREAD

**Issue by kaylumah** [WeAreDotnet/dotnet-creator-cards#135]
The feed of my content does not appear to be processed https://www.wearedotnet.io/kaylumah

**Comment by DeeJayTC** [comment]
Hey! 
can you further say what you mean by not processed? I can see posts and the last like 7 months ago

**Comment by kaylumah** [comment]
@DeeJayTC my post from this week (which is in the feed) is not appearing :)

**Comment by kaylumah** [comment]
The feed https://kaylumah.nl/feed.xml has an entry for 2023-04-13 :)

**Comment by DeeJayTC** [comment]
hmm weird, let me find out why its ignoring that one

**Comment by DeeJayTC** [comment]
I pushed it again, lets see if the next hourly sync catches it

**Comment by DeeJayTC** [comment]
Parsed now @kaylumah can't really tell why it wasn't picked up earlier, can take a bit until its in the cache everywhere and displayed.

**Comment by DeeJayTC** [comment]
Landing page and RSS feed has it already, closing this one here :)

**Comment by kaylumah** [comment]
Thank you, have a great day :)
