### ISSUE TITLE
Profile posts are repeated

### ISSUE THREAD

**Issue by ShadyNagy** [WeAreDotnet/dotnet-creator-cards#153]
**Describe the bug**
- The posts are repeated in the profile, so I fixed this by making the personal RSS without dotnet. 
Is that fine or it should be fixed from your side so 
profile posts = personal

- Images for the posts did not appear so I added them in the RSS so is the site will refresh all the posts?

- Last 2 days posts not appear in my profile

**Screenshots**
![image](https://user-images.githubusercontent.com/6225593/233818197-3986532d-4619-43e3-945a-a1330c60e6df.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 112.0.1

**Comment by DeeJayTC** [comment]
@ShadyNagy Damn its always you having issues, sooo sorry. 

I think at this point its best if i just prune all your posts and have it re-index them completely, especially as you didn't have images before, i'll debug  your new feed once and check it out. Prolly tomorrow, that ok?

**Comment by DeeJayTC** [comment]
mhm @ShadyNagy something is wrong with your feeds in general right now, all links return 404s

**Comment by ShadyNagy** [comment]
@DeeJayTC 
Now it is fine

**Comment by ShadyNagy** [comment]
Thanks, @DeeJayTC 
I will close the issue as it is fixed.
