### ISSUE TITLE
[Bug] Changed Date Format - Feed not updating

### ISSUE THREAD

**Issue by nor0x** [WeAreDotnet/dotnet-creator-cards#169]
**Describe the bug**
Hi all 👋
i'm following up from a discord thread (https://discord.com/channels/1077618323325460572/1097436942339162174/1101264672201650249) i think here is the better place to discuss this specific issue.
It seems that my feed https://www.wearedotnet.io/nor0x is not updating correctly - i have made various changes to the generation of my atom.xml feed to be sure to have the correct date format, as suggested by @DeeJayTC 
![image](https://user-images.githubusercontent.com/3210391/235221172-cf224b77-1e8f-4ac9-91b4-8c0b5e419469.png)

this is the date format i currently have in my feed:

`2022-08-22T15:52:02Z`

unfortunately the feed on my creator profile is not updating and still showing that the posts are from year 0001 -> 122 years ago 
![image](https://user-images.githubusercontent.com/3210391/235221623-b566bc0a-1c36-4e47-9db3-59092911fce6.png)

here is a sample entry data from my feed (https://johnnys.news/atom.xml)
```xml
<!-- sample data from https://johnnys.news/atom.xml -->
<entry>
<id>https://johnnys.news/2022/08/say-hello-to-Maui-ColorPicker/</id>
<updated>2022-08-22T15:52:02Z</updated>
<published>2022-08-22T15:52:02Z</published>
<title>say hello to Maui.ColorPicker</title>
<link rel="alternate" href="https://johnnys.news/2022/08/say-hello-to-Maui-ColorPicker/"/>
<content type="html">
```

would really appreciate a helping hand here, is there anything i need to modify in my feed template?

Thank you!

**Comment by DeeJayTC** [comment]
Can you put your feed in here and send me the result?

https://validator.w3.org/feed/

**Comment by DeeJayTC** [comment]
Nevermind i can do that myself lol....

**Comment by DeeJayTC** [comment]
You can check it yourself @nor0x , the validation fails for various reasons. Also its prolly to large as you have what looks like full website content in there.

**Comment by nor0x** [comment]
thanks a lot @DeeJayTC - i will my way through the issues from the validator! Once i will publish my updated feed, will it appear automatically on https://www.wearedotnet.io/nor0x ?

**Comment by DeeJayTC** [comment]
no, i have to clean it before i think to make sure it re-indexes everything  properly. As it has stuff indexed now but with wrong dates.

**Comment by nor0x** [comment]
alright, i think we are good to go then

![image](https://user-images.githubusercontent.com/3210391/235237151-2bcfc2b0-f0b7-40a8-959f-02ddf7252130.png)


fingers crossed 🤞

**Comment by DeeJayTC** [comment]
I'll try it in like 30 min

**Comment by nor0x** [comment]
awesome, thanks a ton!

**Comment by DeeJayTC** [comment]
![image](https://user-images.githubusercontent.com/4077759/235249419-b58daa2e-7763-4507-9efb-3232771474c9.png)
when cache is expiring next time it should pick it up, or within the next cycle which is in ~30 min (we update feeds every hour on the hour)

**Comment by DeeJayTC** [comment]
@nor0x i can see locally and in DB that its fine and updated, should be reflected on the  page soon

**Comment by nor0x** [comment]
works great! thank you very much @DeeJayTC
