### ISSUE TITLE
[Bug] pierrebelin profile doesn't show content

### ISSUE THREAD

**Issue by matthiasjost** [WeAreDotnet/dotnet-creator-cards#171]
**Describe the bug**
I defined Pierre (@pierrebelin ) as a creator and corrected the creator card's feed type (to dotnet).
I cannot see his content items on his profile: https://www.wearedotnet.io/pierrebelin.

![image](https://user-images.githubusercontent.com/8178852/235346826-a2f8b911-afda-4704-afa0-d915ffd27186.png)

**Comment by matthiasjost** [comment]
It looks like it works now!

**Comment by pierrebelin** [comment]
Thanks you @matthiasjost, works perfectly!
