### ISSUE TITLE
Problem for showing card based on json

### ISSUE THREAD

**Issue by mehdihadeli** [WeAreDotnet/dotnet-creator-cards#178]
Hi,
At first, thanks for creating this great community.
I have some problem with my card based on [this json config](https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/creator-cards/mehdi-hadeli.json):
- My RSS posts don't show up in the [creator profile page](https://www.wearedotnet.io/mehdihadeli)
- `Links` section doesn't show my other social links
- The `Feeds` section on the left shows two feed links, but in the json I just have one feed

**Comment by DeeJayTC** [comment]
Your feed does not have a valid SSL certificate that's why we can't parse it.

**Comment by mehdihadeli** [comment]
@DeeJayTC  I fixed url problem here #180, now feed address in json file is ssl based

**Comment by DeeJayTC** [comment]
Actually yea figured just now I was looking at your old URL but the new one seems to be returning a sorta wrong feed as well? 

If I look at this one -> https://mehdihadeli.com/rss it seems to have some issues, there are only like 2 entries (is that right?) and the date format is wrong it has to be an ISO format. Also your feed has the wrong media type, its sent with text/plain instead of text/xml

**Comment by DeeJayTC** [comment]
Yep, mime type etc is fine but just the date here -> <pubDate>Sat, 29 Apr 2023 00:00:00 GMT</pubDate> is not a valid ISO date at least we had problems parsing that properly in past. Can you update that to like this "2022-09-27 18:00:00.000" or the UTC format?

**Comment by mehdihadeli** [comment]
Thanks, I try to change it to this format

**Comment by DeeJayTC** [comment]
Yea that should work

**Comment by mehdihadeli** [comment]
So, Should I do this change just for my feed, or you will apply this in your parse?

**Comment by DeeJayTC** [comment]
No you have to do that on your end, so your feed needs to send that proper date format.

**Comment by mehdihadeli** [comment]
Thanks it works fine :)
