### ISSUE TITLE
[Bug] Problem with show my card in creators

### ISSUE THREAD

**Issue by meysamhadeli** [WeAreDotnet/dotnet-creator-cards#182]
My card doesn't show in creators section. Also, I completed all links needed in my profile, But my card doesn't show up yet!
Please help me to fix it.

**Comment by DeeJayTC** [comment]
Yea, that will be fixed once we have your feed completely working. "Creator's" are currently identified by having a proper feed.

**Comment by meysamhadeli** [comment]
> Yea, that will be fixed once we have your feed completely working. "Creator's" are currently identified by having a proper feed.

My [feed](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmeysamhadeli.com%2Frss.xml) now is ok and I checked my `rss feed` and it was ok and healthy. It doesn't have any problem. But in the creators section, But still my section is not shown!

**Comment by DeeJayTC** [comment]
Had a few busy days but gonna check that to orrow again, ill get that sorted

**Comment by meysamhadeli** [comment]
> Had a few busy days but gonna check that to orrow again, ill get that sorted

Thanks.

**Comment by DeeJayTC** [comment]
@meysamhadeli got your feed indexed properly now, i did not force a cache refresh but it should be there in an hour or two
