### ISSUE TITLE
[Bug] Problem with load cards in Creators (Browse All)

### ISSUE THREAD

**Issue by meysamhadeli** [WeAreDotnet/dotnet-creator-cards#185]
My Card look exists in `Creators` but when click in `Browse All` and search my card, it doesn't exist! 
I think it's still having a problem in `Browse All` page and doesn't load some creators card.

**Comment by DeeJayTC** [comment]
Oh thats actually a good reminder, sometimes the indexer does not update the creator list in azure search. Still did not have time to fix this. 

Should be able to find you now!

**Comment by meysamhadeli** [comment]
> Oh thats actually a good reminder, sometimes the indexer does not update the creator list in azure search. Still did not have time to fix this.
> 
> Should be able to find you now!

You're welcome, My card is ok now. Thanks.
