### ISSUE TITLE
[Bug] WomenOfDotNet is still referenced in mobile menu

### ISSUE THREAD

**Issue by Layla-P** [WeAreDotnet/dotnet-creator-cards#190]
On mobile devices, the WODN logo and filter are still present.
Please remove.

![image](https://github.com/WeAreDotnet/dotnet-creator-cards/assets/15874598/d36be0c4-6321-4e03-b355-f17a502adc95)

**Comment by DeeJayTC** [comment]
Ahh damn, sorry. Missed that one!
Will be gone on the next deployment.

**Comment by DeeJayTC** [comment]
@Layla-P this should be done now, deployment is going out right now. 
Can you please verify and let us know if everything is fine for you now?

**Comment by DeeJayTC** [comment]
@Layla-P closing this now, please add a new issue if theres anything else.
