### ISSUE TITLE
[Bug] Main content page does not display latest video from YouTube.

### ISSUE THREAD

**Issue by ByteRain0** [WeAreDotnet/dotnet-creator-cards#195]
When going to the main content page https://www.wearedotnet.io/content I can not find the latest video from the YouTube page. Previous video was shown there last time I posted it however the new one can not be found.
The video however can be found on the details page of the profile.
Creator name : [Oleinic Vasilii] (https://www.wearedotnet.io/ByteRain0)
Name of the video : .NET Minimal API part 9 - Pragmatic Endpoint Registry

Update #2 Video cannot be found in the search as well as far as I can see.

**Comment by DeeJayTC** [comment]
The /content page is kinda random, as long as you find a video on your profile it can be found. This part of the page is still undergoing quite am update. 

Also the landing page and /content page only shows 1 video/blog entry by an author at the time.

**Comment by ByteRain0** [comment]
I'll be closing this issue in such case.
