### ISSUE TITLE
[Bug] Check why mail is shown for new creator

### ISSUE THREAD

**Issue by matthiasjost** [WeAreDotnet/dotnet-creator-cards#200]
![image](https://github.com/WeAreDotnet/dotnet-creator-cards/assets/8178852/c0a8a74b-3ec9-4334-8855-e488f65195ed)

**Comment by DeeJayTC** [comment]
He does not have his Github profile configured: https://github.com/devindran

In those cases the Github API returns the email instead of a name.

**Comment by devindran** [comment]
@DeeJayTC I have updated my name in my Github profile. Can my card be refreshed please? Thanks.

**Comment by devindran** [comment]
Looks good now. Thanks. I assumed it would use the name provided in the creator card json file.
