### ISSUE TITLE
[Bug] Not showing me as a creator

### ISSUE THREAD

**Issue by makolyte** [WeAreDotnet/dotnet-creator-cards#207]
**Describe the bug**
I created a [profile ](https://www.wearedotnet.io/makolyte) and have a [creator card](https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/creator-cards/maclain-wiltzer-(mak)-and-yasmin-rodriguez.json), but it's not showing me as a creator.

Name: Maclain Wiltzer

Note: The creator card JSON was created automatically from the previous content creators list that Matthias had made. About a month ago, I went and updated it to the new format.

**To Reproduce**
1. Look at my [profile ](https://www.wearedotnet.io/makolyte) and creator card [creator card](https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/creator-cards/maclain-wiltzer-(mak)-and-yasmin-rodriguez.json). They exist and appear to be correct.
2. Go to [creators ](https://www.wearedotnet.io/creators)
3. Search for "Maclain"
4. No results

**Expected behavior**
Should show me as a creator since I have a creator card + profile.

Furthermore, it should show my latest content. I'm assuming it's not showing anything because it's not seeing me as a creator.

**Comment by DeeJayTC** [comment]
Hey @makolyte 
your feed url's are not working for me and always run in a timeout, thats why you're currently not listed.

**Comment by makolyte** [comment]
Hi @DeeJayTC. After seeing your message, I checked my site and confirmed there was a problem with my host that started last week. So I switched to a new host. That took care of the connectivity problems. I verified that the feed pages are now working properly.
