### ISSUE TITLE
[Bug] - Content creator card not appearing and weird behaviour on Creators view 

### ISSUE THREAD

**Issue by Xelit3** [WeAreDotnet/dotnet-creator-cards#221]
**Describe the bug**
After the submission and merge of the content creator card, apparently my card is showing my feeds and my content is listed in the feed. That's good

However, I'm no able to see my card in the creators view, I've tried loged in and in incognito mode, and in Edge, Chrome and Firefox. 

I appeared only once, then after refreshing I disappeared...

In mobile phone I found the same behaviour: I appeared once, and in the next refresh I disappeared, now in fact each time I try to refresh the page keeps loading infinitely.

**More than a problem of not showing my card, I report this due to the fact that there is erratic behavior on this screen. 
Any cache problem in the response? something like that?**

**To Reproduce**
1. Go to 'Creators'
2. Click on 'Browse all XXX Creators,' _189 in the moment of the bug report_
3. Latest one appears in the top
4. My card is not in the initial preview nor there

**Expected behavior**
In each navigation to this view the same cards should appear.

**Screenshots**
![Image_dektop_1](https://github.com/WeAreDotnet/dotnet-creator-cards/assets/55638917/ff227f89-cbc9-48f2-a0cb-058f8e9dedff)

![Image_dektop_2](https://github.com/WeAreDotnet/dotnet-creator-cards/assets/55638917/7e85952c-1103-47dc-99c4-c00d08ea6e55)

![Image_phone](https://github.com/WeAreDotnet/dotnet-creator-cards/assets/55638917/519a429f-654d-4a78-a96e-f8531cb00333)

**Desktop (please complete the following information):**
 - Windows 11.
 - Browser: Edge, Chrome and Firefox.
 - Version: All of them up to date.

**Smartphone (please complete the following information):**
 - OS: Android 13
 - Browser Edge and Chrome
 - Version: All of them up to date.

**Comment by DeeJayTC** [comment]
![image](https://github.com/WeAreDotnet/dotnet-creator-cards/assets/4077759/24f65c5b-45e1-4b54-9483-cb1b3022c33d)
should be sorted :)

**Comment by Xelit3** [comment]
Hi @DeeJayTC !

Thanks for your reply, now I'm able to see it, but not before, even trying to filter...

In addition, I found more weird behaviours in this screen that I reported trying to help to improve the system.

I hope you find it useful though, it's indeed your platform so your rules anyway...

Regards
