### ISSUE TITLE
[Bug] My blog feed is not showing up

### ISSUE THREAD

**Issue by julioct** [WeAreDotnet/dotnet-creator-cards#226]
**Describe the bug**
I have enabled a feed for my blog and another one for my YouTube channel. The blog one is now showing up on the site.

**To Reproduce**
1. Go to https://www.wearedotnet.io/julioct
2. On the feeds section on bottom left, my blog feed does not show up
3. On the list of posts on right side only YouTube channel videos show up, not my blog posts.

**Expected behavior**
Both YouTube videos and blog posts should show up

**Screenshots**
![image](https://github.com/WeAreDotnet/dotnet-creator-cards/assets/2374270/e4b58bf3-c385-46c3-b6df-bfed40facdf2)

My Card is [here](https://github.com/WeAreDotnet/dotnet-creator-cards/blob/main/creator-cards/julio-casal.json). Copied here:
```json
{
  "name": "Julio Casal",
  "type": "CREATOR",
  "tags": "C#, .NET, Azure, DevOps, Microservices",
  "github": "https://github.com/julioct",
  "channels": [
    {
      "name": "Blog",
      "url": "https://juliocasal.com/blog"
    },        
    {
      "name": "Youtube",
      "url": "https://www.youtube.com/@juliocasal"
    }
  ],
  "feeds": [
    {
      "type": "dotnet",
      "url": "https://juliocasal.com/feed.xml"
    },        
    {
      "type": "dotnet",
      "url": "https://www.youtube.com/feeds/videos.xml?channel_id=UCw8aBxRvQ2ksWNFuO5eHdmA"
    }
  ],
  "projects": [
    {
      "name": "Building Microservices With .NET",
      "description": "Unlock The New Way To Build Cloud Ready .NET Systems At Scale",
      "url": "https://dotnetmicroservices.com"
    }
  ]
}
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 115.0.1901.203

**Additional context**

**Comment by DeeJayTC** [comment]
This  should be fixed now, the next sync should fetch your blog as well, please re-open if blog still does not show up within 24 hours.

**Comment by julioct** [comment]
Thank you!
