### ISSUE TITLE
Include sessionize.com links

### ISSUE THREAD

**Issue by Layla-P** [WeAreDotnet/dotnet-creator-cards#3]
I'd love to sessionize.com speaker pages included on the cards.

**Comment by matthiasjost** [comment]
Thanks, Layla, that's a good suggestion! A lot of people have one. We could either add them as "channels" in the JSON or add sessionize in the JSON as a distinct attribute and then also show an icon on the card. Either way, it makes total sense!

**Comment by DeeJayTC** [comment]
![image](https://user-images.githubusercontent.com/4077759/219868651-9320a783-efb8-406f-8c43-4f8e8c67edb5.png)

Just added to the page :)
Nice suggestion, thanks @Layla-P 

We could later on use that to show things like "Meet this person at conference xyz" on the cards. Lets see what we end up with!

**Comment by gabrieldelaparra** [comment]
StackOverflow as well?

**Comment by AndrewKeepCoding** [comment]
And YouTube as well please.

**Comment by matthiasjost** [comment]
The login is via GitHub. So we have that anyway. StackOverflow could be added. You can include it under channels in your JSON card.

**Comment by DeeJayTC** [comment]
@Layla-P planning to signup as well? 😀

**Comment by matthiasjost** [comment]
@ Layla-P  I sent you a DM on Twitter just to make sure you got the message. Greetings Matthias

**Comment by DeeJayTC** [comment]
Sorted :)
