### ISSUE TITLE
My feed doesn't load

### ISSUE THREAD

**Issue by ursenzler** [WeAreDotnet/dotnet-creator-cards#78]
When navigating to my card (https://www.wearedotnet.io/ursenzler), the feed loader spins forever.
Did I set up the card in the wrong way, or is there a problem with the feed URL, or the feed itself?

Thanks for your help.

**Comment by matthiasjost** [comment]
@DeeJayTC As far as I can see, here is a valid feed. What do you think?

**Comment by DeeJayTC** [comment]
Hey @ursenzler 
just had a look, the problem is actually that your feed is not HTTPS protected and also has a weird redirect: 

your feed date comes from:
-> http://feeds.feedburner.com/planetgeekch 

The URL you gave us:
https://www.planetgeek.ch/feed/

Does a 302 redirect to a non HTTPS page 

That does not work for various security reasons. 

You'd need to give us  a proper https protected feed.

**Comment by ursenzler** [comment]
Thanks for debugging this! I'll change the feed.

**Comment by ursenzler** [comment]
I updated the feed, and @matthiasjost merged the change. But the feed still doesn't show up.
@DeeJayTC, can you please take another look? Many thanks for your work on this site!

**Comment by matthiasjost** [comment]
Can we close this issue?

**Comment by ursenzler** [comment]
The feed still doesn't load :-(

**Comment by matthiasjost** [comment]
We are sorry. We are going to look into it 🙂

**Comment by ursenzler** [comment]
Thanks. No hurry.

**Comment by DeeJayTC** [comment]
Should work now @ursenzler

**Comment by ursenzler** [comment]
Many thanks; the feed works now. I have to check the WordPress settings regarding the image. We set up that WordPress instance over 10years ago...... :-D

**Comment by ursenzler** [comment]
I added a plugin that should add og:image tag.
Let's see what happens. So for now, I'll close this issue.
🙇‍♂️

**Comment by ursenzler** [comment]
Yeah! New content is rendered with an image.
Many thanks for your support and for your work on wearedotnet in general! Great idea.
