### ISSUE TITLE
Blog with multiple authors?

### ISSUE THREAD

**Issue by Piedone** [WeAreDotnet/dotnet-creator-cards#91]
Under [Orchard Dojo](https://orcharddojo.net/) we have a blog with news about, and tutorials related to the open-source ASP.NET Core CMS and framework [Orchard Core](https://orchardcore.net/) (does it ring a bell, @matthiasjost? :)). Is this something suitable to be included on WeAreDotnet, or are only single-person blogs and else allowed?

While the Readme suggests the latter, [the other-cards](https://github.com/WeAreDotnet/dotnet-creator-cards/tree/main/other-cards) folder has a lot of similar multi-author blogs.

**Comment by DeeJayTC** [comment]
Deffo want to have them...the easiest would be if i manually add them or one of you guys signs up and we use a normal creator card where we change the name etc so it doesnt look like an individual. 

Need to check if that would work

**Comment by Piedone** [comment]
Let me know which direction to go then, and I'll submit a PR.

BTW great initiative!

**Comment by DeeJayTC** [comment]
Yea i'll let you know. I'm currently thinking about a "non-individual" creator type, that would be listed under creators we'd index the feeds, etc but people can see that's not an individual person, something like that. 

Can you give me your RSS feed? want to play around with it to see how that could work

**Comment by Piedone** [comment]
Sure, thank you. Here's the RSS: https://orcharddojo.net/rss?projection=47

**Comment by matthiasjost** [comment]
We managed to include resources like .NET foundation. So it will be possible to include yours as well Zoltan. What do you think @DeeJayTC?

**Comment by DeeJayTC** [comment]
Yea its a manual task but i'll get that done the next days

**Comment by DeeJayTC** [comment]
Hey guys, this is still open i know...working on something that has an impact on this. 

We'll have you added together with the patch when we add the project listing. There'll be a page for Orchard  Core  then

**Comment by Piedone** [comment]
Awesome, thank you!

**Comment by Piedone** [comment]
So what should I do here? I don't see any relevant recent change in the code or the docs.

**Comment by matthiasjost** [comment]
Do we have news here @DeeJayTC?

**Comment by DeeJayTC** [comment]
Hups @Piedone that was actually closed by mistake. 

We can do this:

You create a card for Orchard with all the feeds, links and bio. 

I add an account for it, as long as you do not have any "Team" GH account or something like that. 

We did the same for the dotnet blogs.

**Comment by DeeJayTC** [comment]
Id still prefer every creator who writes for you to sign up individually but well....

**Comment by Piedone** [comment]
Thanks, added a PR: https://github.com/WeAreDotnet/dotnet-creator-cards/pull/174

**Comment by Piedone** [comment]
Shouldn't our posts show up under https://www.wearedotnet.io/? They're correctly shown under https://www.wearedotnet.io/Lombiq.

**Comment by matthiasjost** [comment]
Can you reply here @DeeJayTC I am not sure what the idea is here.
Shouldn't it be that feeds defined with type dotnet should be shown also for multi Author blogs?

**Comment by DeeJayTC** [comment]
Well we said if the feeds are not for the "general .NET audience" its rather a personal feed for now until we find a better solution. 

Many of the posts are great and good but rather interesting for just Orchard users which is why i set it to personal. After all we do not want to become some "advertising" platform. 

However no strong feelings and im happy with either and we can set it to dotnet as well.
